### PR TITLE
Testing, Testing, 123

### PR DESCRIPTION
**Pull request by lishaduck**
## Description

> Describe your changes in a sentence or two.

This PR has a bunch of miscellaneous changes, mostly regarding tests.

_**Closes:** #issue_

## Type of Change

- 🧪 Test

### CODE REVIEW

**Comment by lishaduck** [comment]
This isn't done, but I'd like to merge it sooner rather than later.

**Comment by lishaduck** [comment]
`git bisect` says it's 7867f1a370d314f191b0357ee71a20adb2a89b5b that broke the tests. I did some investigating, and it looks like it's going to be a nice, long week... 😉

**Comment by lishaduck** [comment]
Also, I need to re-sort and re-translate the arb files.

**Comment by lishaduck** [comment]
36% codecov w/6[^1] skipped test cases!

[^1]: That's not good, but when I fix them, think of the further codecov increases!

**Review by ParkerH27 — APPROVED** [review]

**Pull request merged**
